# Generated by Django 5.2.12 on 2026-04-02 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('laptop', 'Laptop'), ('mobile', 'Mobile')], max_length=20)),
                ('item_id', models.IntegerField()),
                ('score', models.PositiveSmallIntegerField()),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app.customeraccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('customer', 'item_type', 'item_id'), name='unique_rating_per_customer_product'), models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='rating_score_between_1_and_5')],
            },
        ),
    ]
