# Generated by Django 5.2.12 on 2026-04-02 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW_PRODUCT', 'View Product'), ('ADD_TO_CART', 'Add To Cart'), ('RATE_PRODUCT', 'Rate Product')], max_length=30)),
                ('item_type', models.CharField(blank=True, max_length=20)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('rating_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='app.customeraccount')),
            ],
        ),
    ]
