"""
Django settings for api_gateway project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n%u3jbl=q1n+b(iu^((85tc2naj8(1zl+=ot7^-k+16_df#-z%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'api_gateway.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api_gateway.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

API_GATEWAY_PORT = int(os.getenv('API_GATEWAY_PORT', '8000'))
USER_SERVICE_URL = os.getenv('USER_SERVICE_URL', os.getenv('CUSTOMER_SERVICE_URL', 'http://127.0.0.1:8007'))
CUSTOMER_SERVICE_URL = os.getenv('CUSTOMER_SERVICE_URL', USER_SERVICE_URL)
PRODUCT_SERVICE_URL = os.getenv('PRODUCT_SERVICE_URL', 'http://127.0.0.1:8003')
AI_SERVICE_URL = os.getenv('AI_SERVICE_URL', 'http://127.0.0.1:8005')
ORDER_SERVICE_URL = os.getenv('ORDER_SERVICE_URL', 'http://127.0.0.1:8006')
KB_SERVICE_URL = os.getenv('KB_SERVICE_URL', 'http://127.0.0.1:8010')
PAYMENT_SERVICE_URL = os.getenv('PAYMENT_SERVICE_URL', 'http://127.0.0.1:8008')
SHIPPING_SERVICE_URL = os.getenv('SHIPPING_SERVICE_URL', 'http://127.0.0.1:8009')
VIEWED_EVENT_WINDOW_SECONDS = int(os.getenv('VIEWED_EVENT_WINDOW_SECONDS', '300'))

SERVICE_ENDPOINTS = [
    {
        'service': 'customer',
        'base_url': CUSTOMER_SERVICE_URL,
        'endpoints': [
            {'gateway_path': '/api/customer/register/', 'target_path': '/customer/register/'},
            {'gateway_path': '/api/customer/login/', 'target_path': '/customer/login/'},
            {'gateway_path': '/api/customer/accounts/', 'target_path': '/customer/accounts/'},
            {'gateway_path': '/api/customer/accounts/{customer_id}/', 'target_path': '/customer/accounts/{customer_id}/'},
            {'gateway_path': '/api/customer/carts/', 'target_path': '/customer/carts/'},
            {'gateway_path': '/api/customer/cart-items/', 'target_path': '/customer/carts/items/'},
            {'gateway_path': '/api/customer/cart-items/{cart_item_id}/', 'target_path': '/customer/carts/items/{cart_item_id}/'},
            {'gateway_path': '/api/customer/activities/', 'target_path': '/customer/activities/'},
            {'gateway_path': '/api/customer/ratings/', 'target_path': '/customer/ratings/'},
            {'gateway_path': '/api/customer/search/', 'target_path': '/customer/search/'},
        ],
    },
    {
        'service': 'user-service',
        'base_url': USER_SERVICE_URL,
        'endpoints': [
            {'gateway_path': '/api/staff/register/', 'target_path': '/staff/register/'},
            {'gateway_path': '/api/staff/login/', 'target_path': '/staff/login/'},
            {'gateway_path': '/api/staff/permissions/', 'target_path': '/staff/permissions/'},
            {'gateway_path': '/api/staff/accounts/', 'target_path': '/staff/accounts/'},
            {'gateway_path': '/api/staff/accounts/{staff_id}/', 'target_path': '/staff/accounts/{staff_id}/'},
            {'gateway_path': '/api/staff/items/', 'target_path': '/staff/items/'},
            {'gateway_path': '/api/staff/items/{item_id}/', 'target_path': '/staff/items/{item_id}/'},
        ],
    },
    {
        'service': 'order',
        'base_url': ORDER_SERVICE_URL,
        'endpoints': [
            {'gateway_path': '/api/orders/', 'target_path': '/orders/'},
            {'gateway_path': '/api/orders/checkout/', 'target_path': '/orders/checkout/'},
        ],
    },
    {
        'service': 'payment',
        'base_url': PAYMENT_SERVICE_URL,
        'endpoints': [
            {'gateway_path': '/api/payment/pay', 'target_path': '/payment/pay'},
            {'gateway_path': '/api/payment/status', 'target_path': '/payment/status'},
            {'gateway_path': '/api/payment/methods/', 'target_path': '/payment/methods/'},
            {'gateway_path': '/api/payment/methods/{method_id}/', 'target_path': '/payment/methods/{method_id}/'},
        ],
    },
    {
        'service': 'shipping',
        'base_url': SHIPPING_SERVICE_URL,
        'endpoints': [
            {'gateway_path': '/api/shipping/create', 'target_path': '/shipping/create'},
            {'gateway_path': '/api/shipping/status', 'target_path': '/shipping/status'},
            {'gateway_path': '/api/shipping/methods/', 'target_path': '/shipping/methods/'},
            {'gateway_path': '/api/shipping/methods/{method_id}/', 'target_path': '/shipping/methods/{method_id}/'},
        ],
    },
    {
        'service': 'product',
        'base_url': PRODUCT_SERVICE_URL,
        'endpoints': [
            {'gateway_path': '/api/products/', 'target_path': '/products/'},
            {'gateway_path': '/api/products/{product_id}/', 'target_path': '/products/{product_id}/'},
            {'gateway_path': '/api/products/category-schema/{category_id}/', 'target_path': '/api/categories/{category_id}/attributes/'},
        ],
    },
    {
        'service': 'product-domain',
        'base_url': PRODUCT_SERVICE_URL,
        'endpoints': [
            {'gateway_path': '/api/categories/', 'target_path': '/api/categories/'},
            {'gateway_path': '/api/categories/{category_id}/', 'target_path': '/api/categories/{category_id}/'},
        ],
    },
    {
        'service': 'product-domain',
        'base_url': PRODUCT_SERVICE_URL,
        'endpoints': [
            {'gateway_path': '/api/attributes/', 'target_path': '/api/attributes/'},
            {'gateway_path': '/api/category-attributes/', 'target_path': '/api/category-attributes/'},
            {'gateway_path': '/api/product-attribute-values/', 'target_path': '/api/product-attribute-values/'},
        ],
    },
    {
        'service': 'ai',
        'base_url': AI_SERVICE_URL,
        'endpoints': [
            {'gateway_path': '/api/ai/chat/', 'target_path': '/ai/chat/'},
            {'gateway_path': '/api/ai/recommendations/{customer_id}/', 'target_path': '/ai/recommendations/{customer_id}/'},
        ],
    },
    {
        'service': 'kb',
        'base_url': KB_SERVICE_URL,
        'endpoints': [
            {'gateway_path': '/api/kb/health/', 'target_path': '/api/kb/health/'},
            {'gateway_path': '/api/kb/collect/', 'target_path': '/api/kb/collect/'},
            {'gateway_path': '/api/kb/search/semantic/', 'target_path': '/api/kb/search/semantic/'},
        ],
    },
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
